---
- name: Configurar dominio WebLogic
  hosts: weblogic
  become: true
  vars:
    domain_name: "mydomain"
    admin_user: "weblogic"
    admin_pass: "Welcome1"
    wlst_script: "/tmp/create_domain.py"
  tasks:
    - name: Copiar script WLST al contenedor
      copy:
        src: ../wlst/create_domain.py
        dest: "{{ wlst_script }}"
        mode: 0755

    - name: Ejecutar script WLST en el contenedor
      shell: |
        podman exec {{WEBLOGIC_TARGET}} bash -c "source /u01/oracle/wlserver/server/bin/setWLSEnv.sh && java weblogic.WLST {{ wlst_script }}"
