---
- name: Desplegar WAR en WebLogic
  hosts: weblogic
  become: true
  vars:
    admin_user: "weblogic"
    admin_pass: "Welcome1"
    war_file: "/tmp/"
    weblogic_url: "{{ lookup('env', 'WEBLOGIC_URL') }}"
  tasks:
    - name: Validations
      shell: |
        whoami
        pwd
        ls -ltra

    - name: Copiar WAR al contenedor
      copy:
        src: ../files/myapp.war
        dest: "{{ war_file }}"

    - name: Desplegar la aplicación usando weblogic.Deployer
      shell: |
        podman exec {{WEBLOGIC_TARGET}} bash -c "
        source /opt/oracle/middleware/wlserver/server/bin/setWLSEnv.sh &&
        java weblogic.Deployer \
          -adminurl t3://{{ weblogic_url }}:7001 \
          -username {{ admin_user }} \
          -password {{ admin_pass }} \
          -deploy -name myApp -source {{ war_file }} -targets AdminServer"