---
- name: Copiar script WLST al contenedor
  copy:
    src: wlst/create_domain.py
    dest: /u01/oracle/create_domain.py
    mode: 0755

- name: Ejecutar script WLST en el contenedor
  shell: |
    podman exec weblogic bash -c "source /u01/oracle/wlserver/server/bin/setWLSEnv.sh && java weblogic.WLST /u01/oracle/create_domain.py"
