---
- name: Crear esquema y usuarios en Oracle DB
  hosts: localhost
  gather_facts: no

  vars:
    connect_string: "{{ db_host }}:{{ db_port }}/{{ db_service }}"

  tasks:
    - name: Crear archivo SQL
      copy:
        dest: /tmp/init.sql
        content: |
          CREATE USER prueba IDENTIFIED BY prueba123;
          GRANT CONNECT, RESOURCE TO prueba;

    - name: Ejecutar script SQL en Oracle dentro del contenedor
      shell: |
        podman exec -i {{CONTAINER_NAME}} \
          bash -c "echo '@/tmp/init.sql' | sqlplus {{ db_user }}/{{ db_password }}@{{ connect_string }}"