services:
  oracle-db:
    image: localhost:5000/assist-oracledb:{{DB_TAG_VERSION}}
    container_name: oracledb-21c-{{PROJECT_ID}}
    ports:
      - "{{TNS_LISTEN_PORT}}:1521"
      - "{{APEX_PORT}}:8080"
    environment:
      - ORACLE_PASSWORD=Oracle123
      - APP_USER=appuser
      - APP_USER_PASSWORD=app123
    volumes:
      - oracle-data-{{PROJECT_ID}}:/opt/oracle/oradata
    restart: always

volumes:
  oracle-data-{{PROJECT_ID}}: